// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JavaScript_action() {
	// BEGIN USER CODE
	var x = mx.ui.getContentFrom().path;
	var y = x.split('/');
	var z = y[1].split('.');
	var pageName = z[0];
	return pageName;
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
